version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
            name: Create virtual environment
            command: virtualenv ~/virtualenvs/venv && source ~/virtualenvs/venv/bin/activate

      - run:
          name: Run tests
          command: |
              source ~/virtualenvs/venv/bin/activate
              pip install -r tests/requirements.txt
              python runtests.py
